from selenium import webdriver
import time

driver = webdriver.Chrome()
driver.get(r"F:/pythonProject/python自动化/day01/练习的html/上传文件和下拉列表/autotest.html")
driver.maximize_window()
time.sleep(2)
driver.find_element_by_xpath('//*[@id="accountID"]').send_keys("何保鑫")
time.sleep(2)
driver.find_element_by_xpath('//*[@id="passwordID"]').send_keys("123456")
time.sleep(2)
driver.find_element_by_xpath('//*[@id="areaID"]').send_keys("北京市")
time.sleep(2)
driver.find_element_by_xpath('//*[@id="sexID1"]').click()
time.sleep(2)
driver.find_element_by_xpath('//*[@id="sexID2"]').click()
time.sleep(2)
driver.find_element_by_xpath('//*[@value="summer"]').click()
time.sleep(2)
driver.find_element_by_xpath('//*[@value="winter"]').click()
time.sleep(2)
driver.find_element_by_xpath('//*[@name="file" and @type="file"]').send_keys(r"C:\Users\My\Pictures\武器\我们回家.jpg")
time.sleep(2)
driver.quit()
